### PR TITLE
Update forge to 14.23.5.2855

### PR DESCRIPTION
**Pull request by Nep-Timeline**

### CODE REVIEW

**Comment by mouse0w0** [comment]
I don't think these changes are necessary.

**Comment by Nep-Timeline** [comment]
> I don't think these changes are necessary.

But there will be problems when using 2854
404 NOT FOUND

**Comment by mouse0w0** [comment]
Well, the latest recommended of forge is 14.23.5.2855. But I disagree with your revision of the `mod_author` property.

**Comment by Nep-Timeline** [comment]
> Well, the latest recommended of forge is 14.23.5.2855. But I disagree with your revision of the `mod_author` property.

unimportant

**Comment by mouse0w0** [comment]
Don't leave irrelevant things here.

**Comment by mouse0w0** [comment]
I suggest that you create a new pull request that only modifies the forge version.

**Pull request closed without merging**
